export interface LanguageMeta {
  id: string;
  displayName: string;
  highlighterId: string;
}

const ALIAS_MAP: Record<string, string> = {
  py: "python",
  python3: "python",
  js: "javascript",
  node: "javascript",
  cjs: "javascript",
  mjs: "javascript",
  ts: "typescript",
  jsx: "javascriptreact",
  tsx: "typescriptreact",
  jav: "java",
  kt: "kotlin",
  kts: "kotlin",
  sc: "scala",
  "c++": "cpp",
  cxx: "cpp",
  cc: "cpp",
  hpp: "cpp",
  cs: "csharp",
  "c#": "csharp",
  golang: "go",
  rs: "rust",
  objc: "objectivec",
  "obj-c": "objectivec",
  rb: "ruby",
  pl: "perl",
  pm: "perl",
  jl: "julia",
  rscript: "r",
  hs: "haskell",
  ml: "ocaml",
  fs: "fsharp",
  "f#": "fsharp",
  ex: "elixir",
  exs: "elixir",
  erl: "erlang",
  clj: "clojure",
  cljs: "clojure",
  scm: "lisp",
  elisp: "lisp",
  sh: "bash",
  shell: "bash",
  zsh: "bash",
  posix: "bash",
  ps1: "powershell",
  psm1: "powershell",
  pwsh: "powershell",
  bat: "batch",
  cmd: "batch",
  xhtml: "html",
  sass: "scss",
  less: "scss",
  svg: "xml",
  md: "markdown",
  mdown: "markdown",
  jsonc: "json",
  yml: "yaml",
  dotenv: "ini",
  env: "ini",
  postgresql: "sql",
  postgres: "sql",
  mysql: "sql",
  sqlite: "sql",
  tsql: "sql",
  "t-sql": "sql",
  plsql: "sql",
  gql: "graphql",
  docker: "dockerfile",
  hcl: "terraform",
  tf: "terraform",
  apacheconf: "apache",
  asm: "assembly",
  s: "assembly",
  x86: "assembly",
  x86_64: "assembly",
  arm: "assembly",
  arm64: "assembly",
  wat: "wasm",
  cu: "cuda",
  cuh: "cuda",
  cl: "opencl",
  vert: "glsl",
  frag: "glsl",
  sol: "solidity",
  vy: "vyper",
  makefile: "make",
  mk: "make"
};

const DISPLAY_NAMES: Record<string, string> = {
  python: "Python",
  javascript: "JavaScript",
  typescript: "TypeScript",
  javascriptreact: "JavaScript (JSX)",
  typescriptreact: "TypeScript (TSX)",
  java: "Java",
  kotlin: "Kotlin",
  scala: "Scala",
  c: "C",
  cpp: "C++",
  csharp: "C#",
  go: "Go",
  rust: "Rust",
  swift: "Swift",
  objectivec: "Objective-C",
  dart: "Dart",
  ruby: "Ruby",
  php: "PHP",
  perl: "Perl",
  lua: "Lua",
  julia: "Julia",
  r: "R",
  haskell: "Haskell",
  ocaml: "OCaml",
  fsharp: "F#",
  elixir: "Elixir",
  erlang: "Erlang",
  clojure: "Clojure",
  lisp: "Lisp",
  bash: "Bash / Shell",
  fish: "Fish",
  powershell: "PowerShell",
  batch: "Windows Batch",
  html: "HTML",
  css: "CSS",
  scss: "SCSS",
  xml: "XML",
  markdown: "Markdown",
  json: "JSON",
  json5: "JSON5",
  yaml: "YAML",
  toml: "TOML",
  ini: "INI / dotenv",
  csv: "CSV",
  sql: "SQL",
  graphql: "GraphQL",
  cypher: "Cypher",
  promql: "PromQL",
  dockerfile: "Dockerfile",
  terraform: "Terraform / HCL",
  nginx: "Nginx",
  apache: "Apache",
  assembly: "Assembly",
  wasm: "WebAssembly",
  cuda: "CUDA",
  opencl: "OpenCL",
  glsl: "GLSL",
  hlsl: "HLSL",
  solidity: "Solidity",
  vyper: "Vyper",
  make: "Makefile",
  cmake: "CMake",
  meson: "Meson"
};

export function normalizeLanguageLabel(label: string): string {
  const cleaned = label.trim().toLowerCase();
  if (!cleaned) {
    return "text";
  }
  return ALIAS_MAP[cleaned] ?? cleaned;
}

export function getLanguageDisplayName(label: string): string {
  const normalized = normalizeLanguageLabel(label);
  return DISPLAY_NAMES[normalized] ?? (label.trim() || "Code");
}
